on:
  schedule:
    # Tuesday through Saturday at 9:30 UTC/5:30 ET
    - cron:  '30 9 * 1,2,9-12 *'
  workflow_dispatch:
  
jobs:
  update-data:
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::tidyr
            any::readr
            any::stringr
            any::nflfastR
            any::nflreadr
            any::nflplotR
            any::ggplot2
            any::shadowtext
            any::ggimage
            any::gt
            any::gtExtras
            any::webshot2
            any::cowplot
            any::ggforce
            any::EBImage
            any::magick
            any::sysfonts
            any::showtext
            
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create Preview Cards
        run: Rscript -e 'source("R/Create Card.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
